<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>RcaReloadTrigger</AssemblyName>
    <RootNamespace>RcaReloadTrigger</RootNamespace>
    <BaseOutputPath>$(SolutionDir)bin\</BaseOutputPath>
    <PlatformTarget>x64</PlatformTarget>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

</Project>