<Project>
  <!-- Orchestrate target files to ensure proper build execution -->
  <Import Project="$(SolutionDir)build\targets\timestamp-management.targets" />
  <Import Project="$(SolutionDir)build\targets\hash-generation.targets" />
  <Import Project="$(SolutionDir)build\targets\deployment.targets" />
  <Import Project="$(SolutionDir)build\targets\code-metrics.targets" />
  <Import Project="$(SolutionDir)build\targets\build-notification.targets" />
</Project>
