<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- Indicate this is a test adapter for VS Test Platform -->
    <IsTestAdapter>true</IsTestAdapter>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Metrics" Version="4.14.0" />
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="17.9.0" />
    <PackageReference Include="NUnit" Version="4.0.1" />
  </ItemGroup>

</Project>
