<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>RcaPlugin.Tests</AssemblyName>
    <RootNamespace>RcaPlugin.Tests</RootNamespace>
    <DefineConstants Condition="'$(OS)' != 'Windows_NT'">LINUX_BUILD</DefineConstants>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="../../src/Rca.Contracts/Rca.Contracts.csproj" />
  </ItemGroup>
</Project>