<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>Rca.HotReload.Client</AssemblyName>
    <RootNamespace>Rca.HotReload.Client</RootNamespace>
  </PropertyGroup>

</Project>