using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Rca.BuildMetadata.Generator;

/// <summary>
/// Responsible for generating assembly-level metadata attributes (SourceHash and DeployFolder).
/// Follows SRP by isolating assembly metadata generation from other code generation concerns.
/// </summary>
internal static class AssemblyMetadataEmitter
{
    /// <summary>
    /// Generates and adds assembly metadata attributes to the compilation if the project belongs to a group
    /// and both hash and timestamp are available.
    /// </summary>
    /// <param name="context">The generator execution context for adding source files.</param>
    /// <param name="sourceHash">The source hash to embed (Loader or Runtime hash depending on project group).</param>
    /// <param name="deployFolder">The deploy folder timestamp to embed.</param>
    /// <param name="isLoaderProject">Whether the project belongs to the Loader group.</param>
    /// <param name="isRuntimeProject">Whether the project belongs to the Runtime group.</param>
    /// <remarks>
    /// Assembly metadata is only generated for projects that belong to Loader or Runtime groups.
    /// Both <paramref name="sourceHash"/> and <paramref name="deployFolder"/> must be non-empty for metadata to be emitted.
    /// The generated file is named <c>Rca.AssemblyMetadata.g.cs</c> and contains <c>[assembly: AssemblyMetadata]</c> attributes.
    /// </remarks>
    public static void EmitIfNeeded(
        GeneratorExecutionContext context,
        string? sourceHash,
        string? deployFolder,
        bool isLoaderProject,
        bool isRuntimeProject)
    {
        // Only generate metadata for group projects and only when both hash and timestamp are available
        if (!isLoaderProject && !isRuntimeProject)
            return;

        if (string.IsNullOrWhiteSpace(sourceHash) || string.IsNullOrWhiteSpace(deployFolder))
            return;

        var source = $$"""
            // <auto-generated />
            [assembly: System.Reflection.AssemblyMetadata("SourceHash", "{{sourceHash}}")]
            [assembly: System.Reflection.AssemblyMetadata("DeployFolder", "{{deployFolder}}")]
            namespace Rca.Generated { internal static class __RcaAssemblyMetadataAnchor { } }
            """;

        context.AddSource("Rca.AssemblyMetadata.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    /// <summary>
    /// Reports diagnostics for missing SourceHash or DeployFolder when they are required for group projects.
    /// </summary>
    /// <param name="context">The generator execution context for reporting diagnostics.</param>
    /// <param name="sourceHash">The source hash value (may be null or empty).</param>
    /// <param name="deployFolder">The deploy folder timestamp (may be null or empty).</param>
    /// <param name="isLoaderProject">Whether the project belongs to the Loader group.</param>
    /// <param name="isRuntimeProject">Whether the project belongs to the Runtime group.</param>
    /// <param name="projectName">The MSBuild project name (for diagnostic messages).</param>
    /// <param name="loaderHash">The Loader hash value (for diagnostic context).</param>
    /// <param name="runtimeHash">The Runtime hash value (for diagnostic context).</param>
    /// <param name="isLoaderStr">The raw IsLoaderGroupProject property value (for diagnostic context).</param>
    /// <param name="isRuntimeStr">The raw IsRuntimeGroupProject property value (for diagnostic context).</param>
    public static void ReportMissingMetadataDiagnostics(
        GeneratorExecutionContext context,
        string? sourceHash,
        string? deployFolder,
        bool isLoaderProject,
        bool isRuntimeProject,
        string? projectName,
        string? loaderHash,
        string? runtimeHash,
        string? isLoaderStr,
        string? isRuntimeStr)
    {
        if (!isLoaderProject && !isRuntimeProject)
            return;

        if (string.IsNullOrWhiteSpace(sourceHash))
        {
            var diag = Diagnostic.Create(
                new DiagnosticDescriptor(
                    id: "RCA018",
                    title: "Missing SourceHash property for group project",
                    messageFormat: "SourceHash property is empty for {0} project. IsLoader={1}, IsRuntime={2}, LoaderHash={3}, RuntimeHash={4}, Timestamp={5}",
                    category: "Rca.BuildMetadata.Generator",
                    defaultSeverity: DiagnosticSeverity.Warning,
                    isEnabledByDefault: true),
                Location.None,
                projectName ?? "(unknown)",
                isLoaderStr ?? "false",
                isRuntimeStr ?? "false",
                loaderHash ?? "(empty)",
                runtimeHash ?? "(empty)",
                deployFolder ?? "(empty)");
            context.ReportDiagnostic(diag);
        }

        if (string.IsNullOrWhiteSpace(deployFolder))
        {
            var diag = Diagnostic.Create(
                new DiagnosticDescriptor(
                    id: "RCA019",
                    title: "Missing RcaHotReloadTimestamp property for group project",
                    messageFormat: "RcaHotReloadTimestamp property is empty for {0} project. Cannot generate assembly metadata.",
                    category: "Rca.BuildMetadata.Generator",
                    defaultSeverity: DiagnosticSeverity.Warning,
                    isEnabledByDefault: true),
                Location.None,
                projectName ?? "(unknown)");
            context.ReportDiagnostic(diag);
        }
    }
}

