using System;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Rca.BuildMetadata.Generator;

[Generator]
public sealed class BuildMetadataGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        // No initialization required at this time - updated for timestamp pattern support
    }

    public void Execute(GeneratorExecutionContext context)
    {
        // Read MSBuild property made visible via CompilerVisibleProperty
        if (!context.AnalyzerConfigOptions.GlobalOptions.TryGetValue("build_property.RcaSourceHashLength", out var lengthStr))
        {
            // Property must be provided explicitly by MSBuild (Directory.Build.props). Do not fallback to defaults.
            var diag = Diagnostic.Create(new DiagnosticDescriptor(
                id: "RCA001",
                title: "Missing build property: RcaSourceHashLength",
                messageFormat: "MSBuild property 'RcaSourceHashLength' must be defined (e.g. in Directory.Build.props).",
                category: "Rca.BuildMetadata.Generator",
                defaultSeverity: DiagnosticSeverity.Error,
                isEnabledByDefault: true), Location.None);
            context.ReportDiagnostic(diag);
            return;
        }

        if (!int.TryParse(lengthStr, out var length) || length <= 0)
        {
            var diag = Diagnostic.Create(new DiagnosticDescriptor(
                id: "RCA002",
                title: "Invalid build property: RcaSourceHashLength",
                messageFormat: "MSBuild property 'RcaSourceHashLength' must be a positive integer. Current value: '{0}'",
                category: "Rca.BuildMetadata.Generator",
                defaultSeverity: DiagnosticSeverity.Error,
                isEnabledByDefault: true), Location.None, lengthStr ?? "(null)");
            context.ReportDiagnostic(diag);
            return;
        }

        // Read timestamp pattern property
        if (!context.AnalyzerConfigOptions.GlobalOptions.TryGetValue("build_property.RcaTimestampPattern", out var patternStr))
        {
            // Property must be provided explicitly by MSBuild (Directory.Build.props). Do not fallback to defaults.
            var diag = Diagnostic.Create(new DiagnosticDescriptor(
                id: "RCA003",
                title: "Missing build property: RcaTimestampPattern",
                messageFormat: "MSBuild property 'RcaTimestampPattern' must be defined (e.g. in Directory.Build.props).",
                category: "Rca.BuildMetadata.Generator",
                defaultSeverity: DiagnosticSeverity.Error,
                isEnabledByDefault: true), Location.None);
            context.ReportDiagnostic(diag);
            return;
        }

        if (string.IsNullOrWhiteSpace(patternStr))
        {
            var diag = Diagnostic.Create(new DiagnosticDescriptor(
                id: "RCA004",
                title: "Invalid build property: RcaTimestampPattern",
                messageFormat: "MSBuild property 'RcaTimestampPattern' must be a non-empty string. Current value: '{0}'",
                category: "Rca.BuildMetadata.Generator",
                defaultSeverity: DiagnosticSeverity.Error,
                isEnabledByDefault: true), Location.None, patternStr ?? "(null)");
            context.ReportDiagnostic(diag);
            return;
        }

        var src = $$"""
// <auto-generated />
namespace Rca.Generated
{
    /// <summary>
    /// Build-time metadata surfaced to runtime via Source Generator.
    /// Single source of truth is MSBuild properties.
    /// </summary>
    public static class RcaBuildMetadata
    {
        /// <summary>
        /// Length of the short source hash used for Loader/Runtime groups.
        /// </summary>
        public static int SourceHashLength => {{length}};

        /// <summary>
        /// Timestamp pattern for build output directory names (e.g., "yyyyMMdd_HHmmss").
        /// </summary>
        public static string TimestampPattern => "{{patternStr}}";
    }
}
""";

        context.AddSource("RcaBuildMetadata.g.cs", SourceText.From(src, Encoding.UTF8));
    }
}


