using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Rca.BuildMetadata.Generator;

/// <summary>
/// Responsible for generating the RcaBuildMetadata static class that exposes build-time constants.
/// Follows SRP by isolating build metadata class generation from assembly metadata generation.
/// </summary>
internal static class BuildMetadataClassEmitter
{
  /// <summary>
  /// Generates the RcaBuildMetadata class if the current project is Rca.Contracts.
  /// This class provides a single source of truth for build-time configuration values.
  /// </summary>
  /// <param name="context">The generator execution context for adding source files.</param>
  /// <param name="properties">The validated build properties to embed in the generated class.</param>
  /// <remarks>
  /// WHY: Only Rca.Contracts should emit this class to avoid type conflicts when multiple projects
  /// reference Rca.BuildMetadata.Generator. The generated class exposes MSBuild property values
  /// as static readonly properties, making them available at runtime without hardcoding.
  /// </remarks>
  public static void EmitIfNeeded(GeneratorExecutionContext context, BuildProperties properties)
  {
    // Only emit for Rca.Contracts to avoid type conflicts
    var shouldEmit = string.Equals(properties.ProjectName, "Rca.Contracts", StringComparison.OrdinalIgnoreCase);
    if (!shouldEmit)
      return;

    // Convert semicolon-separated project lists to C# string array literals
    var loaderArray = string.IsNullOrWhiteSpace(properties.LoaderProjectsList)
        ? "System.Array.Empty<string>()"
        : $"new[] {{ \"{string.Join("\", \"", properties.LoaderProjectsList!.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries))}\" }}";

    var runtimeArray = string.IsNullOrWhiteSpace(properties.RuntimeProjectsList)
        ? "System.Array.Empty<string>()"
        : $"new[] {{ \"{string.Join("\", \"", properties.RuntimeProjectsList!.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries))}\" }}";

    var source = $$"""
            // <auto-generated />
            namespace Rca.Generated
            {
                /// <summary>
                /// Build-time metadata surfaced to runtime via Source Generator.
                /// Single source of truth is MSBuild properties.
                /// </summary>
                public static class RcaBuildMetadata
                {
                    /// <summary>
                    /// Length of the short source hash used for Loader/Runtime groups.
                    /// </summary>
                    public static int SourceHashLength => {{properties.SourceHashLength}};

                    /// <summary>
                    /// Timestamp pattern for build output directory names (e.g., "yyyyMMdd_HHmmss").
                    /// </summary>
                    public static string TimestampPattern => "{{properties.TimestampPattern}}";

                    /// <summary>
                    /// Directory where Revit Addins and timestamp subfolders are located.
                    /// </summary>
                    public static string RevitAddinsDir => @"{{properties.RevitAddinsDir}}";

                    /// <summary>
                    /// Revit version used for deployment folder paths.
                    /// </summary>
                    public static string RevitVersion => "{{properties.RevitVersion}}";

                    /// <summary>
                    /// Directory where integration test builds are deployed.
                    /// </summary>
                    public static string TestDeployRoot => @"{{properties.TestDeployRoot}}";

                    /// <summary>
                    /// Root directory where RCA logs are written.
                    /// </summary>
                    public static string LogRoot => @"{{properties.LogRoot}}";

                    /// <summary>
                    /// Path to Revit libraries directory.
                    /// </summary>
                    public static string RevitLibsPath => @"{{properties.RevitLibsPath}}";

                    /// <summary>
                    /// Named pipe for loader and UI commands.
                    /// </summary>
                    public static string CommandPipeName => @"{{properties.CommandPipeName}}";

                    /// <summary>
                    /// Named pipe for UI logging transport.
                    /// </summary>
                    public static string LogPipeName => "{{properties.LogPipeName}}";

                    /// <summary>
                    /// Path to Timestamp file used to coordinate deploy folders.
                    /// </summary>
                    public static string TimestampFile => @"{{properties.TimestampFile}}";

                    /// <summary>
                    /// Sticky TTL (seconds) for timestamp reuse.
                    /// </summary>
                    public static int StickyStampSeconds => {{properties.StickyStampSeconds}};

                    /// <summary>
                    /// Flag indicating whether to force a fresh timestamp for the build.
                    /// </summary>
                    public static bool ForceNewStamp => {{properties.ForceNewStamp.ToString().ToLowerInvariant()}};

                    /// <summary>
                    /// List of project names in the Loader group (Single Source of Truth from MSBuild).
                    /// </summary>
                    public static string[] LoaderProjects => {{loaderArray}};

                    /// <summary>
                    /// List of project names in the Runtime group (Single Source of Truth from MSBuild).
                    /// </summary>
                    public static string[] RuntimeProjects => {{runtimeArray}};
                }
            }
            """;

    context.AddSource("RcaBuildMetadata.g.cs", SourceText.From(source, Encoding.UTF8));
  }
}

