<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <!-- Recommended for analyzer/source-generator projects to enable extended rules -->
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsPackable>false</IsPackable>
    <EnableRoslynAnalyzers>true</EnableRoslynAnalyzers>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceNETAnalyzers>true</EnforceNETAnalyzers>
    <AssemblyName>Rca.BuildMetadata.Generator</AssemblyName>
    <OutputType>Library</OutputType>
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="8.0.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Rca.BuildMetadata.Generator.Tests" />
  </ItemGroup>

</Project>


