name: Compile

# Trigger this workflow on any push to any branch or on pull requests
on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  compile:
    name: Compile
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x 

      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}

      - name: Restore dependencies
        run: dotnet restore rca-plugin.sln

      - name: Build solution
        run: dotnet build rca-plugin.sln --no-restore --configuration Release